drop table test.Person;
create table test.Person (id bigint generated by default as identity, name varchar(255), primary key (id));
insert into test.Person (id, name) values (default, 'Irina Petrova');