drop table test.Person;
create table test.Person (id bigint generated by default as identity, name varchar(255), primary key (id));
select person0_.id as id1_0_, person0_.name as name2_0_ from test.Person person0_;
insert into test.Person (id, name) values (default, 'Irina Petrova');
values identity_val_local();